# ---- base system ----
base
linux
linux-firmware
intel-ucode
amd-ucode
sof-firmware
alsa-ucm-conf
mkinitcpio
mkinitcpio-archiso
arch-install-scripts
sudo
polkit
openssl
zram-generator
plymouth
man-db
man-pages
less
which
nano
vim
bash-completion
inetutils
pciutils
usbutils
fastfetch
fakeroot
pacman-contrib
git
# ---- hardware / services ----
networkmanager
bluez
bluez-utils
pipewire
pipewire-pulse
pipewire-alsa
wireplumber
libpulse
power-profiles-daemon
ufw
brightnessctl
mesa
virtualbox-guest-utils
# ---- disks / installer backend ----
gptfdisk
parted
dosfstools
e2fsprogs
btrfs-progs
exfatprogs
ntfs-3g
rsync
squashfs-tools
efibootmgr
gparted
# ---- graphical stack / Kocmoc shell ----
greetd
cage
labwc
xorg-xwayland
waybar
fuzzel
mako
libnotify
swaybg
swayidle
swaylock
grim
slurp
wl-clipboard
wlr-randr
polkit-gnome
xdg-user-dirs
xdg-utils
xdg-desktop-portal
xdg-desktop-portal-wlr
xdg-desktop-portal-gtk
python
python-gobject
gtk4
gtk4-layer-shell
# ---- look ----
inter-font
ttf-jetbrains-mono
ttf-nerd-fonts-symbols
noto-fonts
noto-fonts-emoji
papirus-icon-theme
adwaita-icon-theme
# ---- applications ----
foot
thunar
thunar-volman
thunar-archive-plugin
gvfs
gvfs-mtp
udisks2
tumbler
mousepad
ristretto
xarchiver
p7zip
unzip
zip
galculator
gnome-system-monitor
firefox
