[Unit]
Description=Kocmoc OS live session setup
ConditionKernelCommandLine=archisobasedir
Before=greetd.service display-manager.service
After=systemd-sysusers.service

[Service]
Type=oneshot
RemainAfterExit=yes
ExecStart=/usr/lib/kocmoc/kocmoc-live-setup

[Install]
WantedBy=multi-user.target
